### ISSUE TITLE
Problema com a porta serial

### ISSUE THREAD

**Issue by davisouzaluna** [davifurao/Sistema-distribuido#1]
Foi consertado o código(a partir da adição de uma biblioteca do ESP8266). Entretanto o erro de porta aparece no código, mostrando como se a mesma estivesse cheia ou não conectada.

O erro é:

Arduino: 1.8.19 (Windows Store 1.8.57.0) (Windows 10), Placa:"NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Disabled (new aborts on oom), Disabled, All SSL ciphers (most compatible), 32KB cache + 32KB IRAM (balanced), Use pgm_read macros for IRAM/PROGMEM, 4MB (FS:3MB OTA:~512KB), 2, v2 Lower Memory, Disabled, None, Only Sketch, 115200"

Executable segment sizes:

ICACHE : 32768           - flash instruction cache 

IROM   : 249188          - code in flash         (default or ICACHE_FLASH_ATTR) 

IRAM   : 26729   / 32768 - code in IRAM          (IRAM_ATTR, ISRs...) 

DATA   : 1520  )         - initialized variables (global, static) in RAM/HEAP 

RODATA : 1212  ) / 81920 - constants             (global, static) in RAM/HEAP 

BSS    : 25776 )         - zeroed variables      (global, static) in RAM/HEAP 

O sketch usa 278649 bytes (26%) de espaço de armazenamento para programas. O máximo são 1044464 bytes.

Variáveis globais usam 28508 bytes (34%) de memória dinâmica, deixando 53412 bytes para variáveis locais. O máximo são 81920 bytes.

esptool.py v3.0

Serial port COM3

Connecting...

Traceback (most recent call last):

  File "C:\Users\Davi\Documents\ArduinoData\packages\esp8266\hardware\esp8266\3.0.2/tools/upload.py", line 66, in <module>

    esptool.main(cmdline)

  File "C:/Users/Davi/Documents/ArduinoData/packages/esp8266/hardware/esp8266/3.0.2/tools/esptool\esptool.py", line 3552, in main

    esp.connect(args.before, args.connect_attempts)

  File "C:/Users/Davi/Documents/ArduinoData/packages/esp8266/hardware/esp8266/3.0.2/tools/esptool\esptool.py", line 519, in connect

    last_error = self._connect_attempt(mode=mode, esp32r0_delay=False)

  File "C:/Users/Davi/Documents/ArduinoData/packages/esp8266/hardware/esp8266/3.0.2/tools/esptool\esptool.py", line 499, in _connect_attempt

    self.sync()

  File "C:/Users/Davi/Documents/ArduinoData/packages/esp8266/hardware/esp8266/3.0.2/tools/esptool\esptool.py", line 438, in sync

    timeout=SYNC_TIMEOUT)

  File "C:/Users/Davi/Documents/ArduinoData/packages/esp8266/hardware/esp8266/3.0.2/tools/esptool\esptool.py", line 376, in command

    self.write(pkt)

  File "C:/Users/Davi/Documents/ArduinoData/packages/esp8266/hardware/esp8266/3.0.2/tools/esptool\esptool.py", line 339, in write

    self._port.write(buf)

  File "C:/Users/Davi/Documents/ArduinoData/packages/esp8266/hardware/esp8266/3.0.2/tools/pyserial\serial\serialwin32.py", line 325, in write

    raise SerialTimeoutException('Write timeout')

serial.serialutil.SerialTimeoutException: Write timeout

a porta serial serial.serialutil.SerialTimeoutException: Write timeout

 selecionada não existe ou sua placa não está conectada

Este relatório teria mais informações com
"Mostrar a saida detalhada durante a compilação"
opção pode ser ativada em "Arquivo -> Preferências"

Não sei se é alguma configuração das portas do meu pc ou simplesmente um problema de versão

A arquitetura da comunicação está correta. Somente há esse erro. Provavelmente terei que realizar uma construção do arduíno no tinkercad ou simulIDE.

**Comment by davisouzaluna** [comment]
O problema ocorreu pois precisava de uma conexão física para estabelecer uma conexão com a rede e realizar o envio dos dados. A Issue será fechada quando for confirmada com o arduino propriamente dito.

**Comment by davisouzaluna** [comment]
Foi conectado com o arduíno, mas como eu não tenho conhecimento no que tange aos componentes de software(como por exemplo, eu descobri ontem que, quando vai se usar um módulo ESP8266, é preciso usar resistores ou um regulador de tensão). No mais, acho pertinente o fechamento da issue, caso ache necessário, eu recomendo abrir outa issue, para fins de organização(pois para esse problema, têm-se um objetivo diferente, que é montar de maneira correta o arduíno).
